WYsystem/Models/w_admin.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WYsystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_admin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public w_admin()
        {
            this.w_announcement = new HashSet<w_announcement>();
            this.w_user_paymoney = new HashSet<w_user_paymoney>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string pass { get; set; }
        public string nickname { get; set; }
        public Nullable<int> power { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<w_announcement> w_announcement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<w_user_paymoney> w_user_paymoney { get; set; }
    }
}

WYsystem/Controllers/WadminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WYsystem.Filter;
using WYsystem.Models;

namespace WYsystem.Controllers
{
    [AdminAuthen]
    public class WadminController : Controller
    {
        private wyEntities db = new wyEntities();

        // GET: Wadmin
        public ActionResult Index()
        {
            return View(db.w_admin.Where(p => p.power == 1 || p.power == 2).ToList());
        }

        //用户首页
        public ActionResult UserIndex()
        {
            return View(db.w_admin.Where(p=>p.power == 0).ToList());
        }

        //用户编辑模块
        public ActionResult UserEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            w_admin w_admin = db.w_admin.Find(id);
            if (w_admin == null)
            {
                return HttpNotFound();
            }
            return View(w_admin);
        }

        //以get方式提交删除数据
        public ActionResult UserDelete(int id)
        {
            w_admin w_admin = db.w_admin.Find(id);
            db.w_admin.Remove(w_admin);
            db.SaveChanges();
            return RedirectToAction("UserIndex");
        }

        // GET: Wadmin/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            w_admin w_admin = db.w_admin.Find(id);
            if (w_admin == null)
            {
                return HttpNotFound();
            }
            return View(w_admin);
        }

        // GET: Wadmin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Wadmin/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性。有关
        // 详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        public ActionResult Create([Bind(Include = "id,username,pass,nickname,power,createtime")] w_admin w_admin)
        {
            if (ModelState.IsValid)
            {
                db.w_admin.Add(w_admin);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(w_admin);
        }

        // GET: Wadmin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            w_admin w_admin = db.w_admin.Find(id);
            if (w_admin == null)
            {
                return HttpNotFound();
            }
            return View(w_admin);
        }

        // POST: Wadmin/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性。有关
        // 详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        public ActionResult Edit([Bind(Include = "id,username,pass,nickname,power,createtime")] w_admin w_admin)
        {
            if (ModelState.IsValid)
            {
                db.Entry(w_admin).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(w_admin);
        }

        [HttpPost]
        public ActionResult UserEdits([Bind(Include = "id,username,pass,nickname,power,createtime")] w_admin w_admin)
        {
            if (ModelState.IsValid)
            {
                db.Entry(w_admin).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("UserIndex");
            }
            return View(w_admin);
        }

        // GET: Wadmin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            w_admin w_admin = db.w_admin.Find(id);
            if (w_admin == null)
            {
                return HttpNotFound();
            }
            return View(w_admin);
        }
        //以get方式提交删除数据
        public ActionResult DeleteConfirmed(int id)
        {
            w_admin w_admin = db.w_admin.Find(id);
            db.w_admin.Remove(w_admin);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WYsystem/Views/Wadmin/Create.cshtml
@model WYsystem.Models.w_admin

@{
    ViewBag.Title = "Create User";
    Layout = "~/Views/Shared/_BackAdmin.cshtml";
}


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Admin</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.pass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.pass, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.pass, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nickname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nickname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nickname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.power, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.power, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.power, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.createtime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.createtime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.createtime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WYsystem/Views/Wadmin/Delete.cshtml
@model WYsystem.Models.w_admin

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_BackAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Do you want to delete this?</h3>
<div>
    <h4>Admin</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.pass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nickname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nickname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.power)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.power)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.createtime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.createtime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WYsystem/Views/Wadmin/Details.cshtml
@model WYsystem.Models.w_admin

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_BackAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Admin</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.pass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nickname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nickname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.power)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.power)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.createtime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.createtime)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WYsystem/Views/Wadmin/Edit.cshtml
@model WYsystem.Models.w_admin

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_BackAdmin.cshtml";
}

<div class="container-fluid">
    <div class="row cm-fix-height">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading" style="margin-bottom:20px"><h2>Edit Information</h2></div>
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.id)

                        <div class="form-group">
                            @Html.LabelFor(model => model.username, "Username", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.username, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.pass, "Password", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.pass, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.pass, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.nickname, "Nickname", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.nickname, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.nickname, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group"  style="display:none;">
                            @Html.LabelFor(model => model.power, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <!--
                                    power = 1 admin
                                    power = 3 super 
                                   -->
                                <select name="power" class="form-control" style="display:none;">
                                    <option value="1">Admin</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="save" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

WYsystem/Views/Wadmin/Index.cshtml
@model IEnumerable<WYsystem.Models.w_admin>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_BackAdmin.cshtml";
}

<div class="container-fluid">
    <div class="row cm-fix-height">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading"><h2>Admin</h2></div>
                <div class="panel-body">
                    <table class="table">
                        <tr>
                            <th>
                                Admin
                            </th>
                            <th>
                                Password
                            </th>
                            <th>
                                Name
                            </th>
                            <th>
                                Time
                            </th>
                            <th>Setting</th>
                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.username)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.pass)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.nickname)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.createtime)
                                </td>
                                <td>
                                    <a href="/Wadmin/Edit/@item.id" class="btn btn-success">Change Password</a>
                                    |
                                    <a href="/Wadmin/DeleteConfirmed/@item.id" onclick="return confirm('Do you want to delete?')" class="btn btn-danger">Delete</a>

                                </td>
                            </tr>
                        }

                    </table>
                    <form action="/Wadmin/Create" style="margin-top:40px;" method="post">
                        <table class="table">
                            <tr>
                                <td>Admin：</td>
                                <td>
                                    <input class="form-control" value="" name="username" required placeholder="admin" />
                                </td>
                            </tr>
                            <tr>
                                <td>Password：</td>
                                <td>
                                    <input class="form-control" value="" name="pass" required placeholder="password" />
                                </td>
                            </tr>
                            <tr>
                                <td>Name：</td>
                                <td>
                                    <input class="form-control" value="" name="nickname" required placeholder="name" />
                                </td>
                            </tr>
                            <tr style="display:none;">
                                <td>Power：</td>
                                <td>
                                    <select name="power" class="form-control">
                                        <option value="1">Admin</option>
                                    </select>
                                </td>
                            </tr>
                            <input type="hidden" name="createtime" value='@DateTime.Now.ToString("yyyy-MM-dd")' />
                            <tr>
                                <td colspan="2" align="center">
                                    <input type="submit" value="保存" class="btn btn-default" />
                                </td>
                            </tr>
                        </table>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

WYsystem/Views/Wadmin/UserEdit.cshtml
@model WYsystem.Models.w_admin

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_BackAdmin.cshtml";
}

<div class="container-fluid">
    <div class="row cm-fix-height">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading" style="margin-bottom:20px"><h2>Change Password</h2></div>
                @using (Html.BeginForm("UserEdits", "Wadmin"))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.id)

                        <div class="form-group">
                            @Html.LabelFor(model => model.username, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.username, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.pass, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.pass, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.pass, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.nickname, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.nickname, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.nickname, "", new { @class = "text-danger" })
                                <input type="hidden" name="power" value="0" />
                                <input type="hidden" name="createtime" value="@Model.createtime" />
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="save" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

WYsystem/Views/Wadmin/UserIndex.cshtml
@model IEnumerable<WYsystem.Models.w_admin>

@{
    ViewBag.Title = "User Center";
    Layout = "~/Views/Shared/_BackAdmin.cshtml";
}

<div class="container-fluid">
    <div class="row cm-fix-height">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading"><h2>User Center</h2></div>
                <div class="panel-body">
                    <table class="table">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.username)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.nickname)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.createtime)
                            </th>
                            <th>Setting</th>
                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.username)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.nickname)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.createtime)
                                </td>
                                <td>
                                    @Html.ActionLink("Cange Password", "UserEdit", new { id = item.id }) |
                                    <a href="/Wadmin/UserDelete/@item.id" onclick="return confirm('Do you want to delete?')">Delete</a>

                                </td>
                            </tr>
                        }

                    </table>
                </div>
            </div>
        </div>
    </div>
</div>